test1 <- read.table('household_power_consumption.txt',header=TRUE,sep=';')
test2 <- split(test1,test1$Date)
test3 <- rbind(test2$'1/2/2007',test2$'2/2/2007')
test4 <- paste(test3$Date,test3$Time)
test5 <- strptime(test4,'%d/%m/%Y %H:%M:%S')
test6 <- as.numeric(as.character(test3$Sub_metering_1))
test7 <- as.numeric(as.character(test3$Sub_metering_2))
test8 <- as.numeric(as.character(test3$Sub_metering_3))
png('plot3.png',width=480,height=480)
plot(test5,test6,type='l',xlab='',ylab='Energy sub metering',col='black')
lines(test5,test7,col='Red')
lines(test5,test8,col='Blue')
legend("topright",col=c('black','red','blue'),legend=c('Sub_metering_1','Sub_metering_2','Sub_metering_3'),lty=c('solid','solid','solid'))
dev.off()